import { Link } from "react-router-dom";
import { ArrowRight, ArrowUpRight, BookOpen, Braces, Code2, Database, FolderOpen, Layers3, Plus, Server, Sparkles } from "lucide-react";
import { curriculum } from "../data/curriculum.js";

export function SubjectHome({ notes }) {
  const subject = curriculum[0];
  const topicCount = subject.groups.reduce((total, group) => total + group.topics.length, 0);
  return <div className="mx-auto max-w-[1080px] px-5 pb-12 pt-9 sm:px-9 sm:pt-12">
    <p className="flex items-center gap-2 text-[10px] font-medium uppercase tracking-[1.8px] text-[#87917f]"><Sparkles size={13}/> Your learning space</p>
    <div className="mt-4 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><h1 className="font-serif text-4xl tracking-[-1.5px] text-[#2f342e] sm:text-5xl">Make room for<br/><em className="font-normal text-[#7c9076]">what you’re learning.</em></h1><p className="mt-4 max-w-md text-sm leading-6 text-[#81877d]">A considered home for your notes, organized around the subjects you want to understand.</p></div><span className="text-[11px] text-[#9a9e94]">{notes.length} saved {notes.length===1?'note':'notes'}</span></div>
    <div className="mb-3 mt-11 flex items-center justify-between"><h2 className="font-serif text-[25px] text-[#363b34]">Your subjects</h2><span className="text-[10px] text-[#a0a398]">{curriculum.length} subject</span></div>
    <Link to={subject.path} className="group relative block overflow-hidden rounded-2xl border border-[#e4e8df] bg-white p-5 transition hover:-translate-y-0.5 hover:shadow-xl hover:shadow-[#394632]/[0.07] sm:p-7"><div className="absolute -right-10 -top-24 size-72 rounded-full border border-[#eaf0e6]"/><div className="absolute -right-2 -top-16 size-56 rounded-full border border-[#eaf0e6]"/><div className="relative flex flex-col gap-8 sm:flex-row sm:items-center sm:justify-between"><div className="max-w-lg"><div className="mb-5 flex items-center gap-3"><span className="grid size-12 place-items-center rounded-[14px] bg-[#edf2e9] text-[#647b5e]"><Code2 size={23}/></span><span className="rounded-full bg-[#f5f7f2] px-3 py-1.5 text-[9px] font-semibold uppercase tracking-[1.1px] text-[#829078]">Subject 01</span></div><h3 className="font-serif text-3xl text-[#323830]">{subject.name}</h3><p className="mt-2 text-xs text-[#92968c]">{subject.description}</p><div className="mt-6 flex flex-wrap gap-2">{subject.groups.map(group=><span key={group.id} className="rounded-full border border-[#ecefe9] bg-white/90 px-3 py-1.5 text-[10px] text-[#72796d]">{group.name}</span>)}</div></div><div className="flex items-center justify-between gap-6 border-t border-[#eff1ec] pt-4 sm:flex-col sm:items-end sm:border-0 sm:pt-0"><div className="text-right"><span className="block font-serif text-3xl text-[#526650]">{topicCount}</span><span className="text-[9px] uppercase tracking-[1px] text-[#a0a398]">learning paths</span></div><span className="flex items-center gap-2 rounded-lg bg-[#526650] px-4 py-3 text-[10px] font-semibold text-white transition group-hover:bg-[#425440]">Open subject <ArrowRight size={14}/></span></div></div></Link>
    <p className="mt-5 flex items-center gap-2 text-[10px] text-[#a0a398]"><Plus size={13}/> Your subject list can grow whenever you’re ready.</p>
  </div>;
}

export function ComputerScience({ notes }) {
  const subject = curriculum[0];
  const icons = { "core-subjects": Layers3, "web-development": Braces };
  return <div className="mx-auto max-w-[1080px] px-5 pb-12 pt-8 sm:px-9 sm:pt-11">
    <Link to="/" className="mb-7 inline-flex items-center gap-2 text-[10px] text-[#858d80] hover:text-[#51664f]"><ArrowLeft size={14}/> All subjects</Link>
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-3 flex items-center gap-2 text-[10px] font-medium uppercase tracking-[1.6px] text-[#87917f]"><Code2 size={13}/> Your subject</p><h1 className="font-serif text-4xl tracking-[-1.4px] text-[#2f342e] sm:text-5xl">Computer Science<span className="text-[#8ca084]">.</span></h1><p className="mt-3 text-xs text-[#858a80]">Choose a learning path and pick up where curiosity takes you.</p></div><div className="flex items-center gap-2 text-[10px] text-[#9a9e94]"><BookOpen size={14}/>{notes.length} notes saved</div></div>
    <div className="mt-10 grid gap-5 lg:grid-cols-2">{subject.groups.map((group,index)=>{const Icon=icons[group.id]||FolderOpen;const count=group.topics.reduce((sum,topic)=>sum+notes.filter(note=>note.subject===topic.name).length,0);return <section key={group.id} className="rounded-2xl border border-[#e7e9e2] bg-white p-5 sm:p-6"><div className="flex items-start justify-between"><span className={`grid size-11 place-items-center rounded-[13px] ${index===0?'bg-[#eef2e9] text-[#71866a]':'bg-[#eef2f4] text-[#6f8d9c]'}`}><Icon size={20}/></span><span className="text-[9px] uppercase tracking-[1.2px] text-[#a5a89f]">{group.topics.length} {group.topics.length===1?'topic':'topics'}</span></div><h2 className="mt-5 font-serif text-[25px] text-[#343a32]">{group.name}</h2><p className="mt-1 text-[11px] text-[#93978d]">{group.description}</p><div className="mt-5 grid gap-2">{group.topics.map(topic=>{const TopicIcon=topic.id==='mongodb'?Database:topic.id==='dsa'?Braces:Server;const topicNotes=notes.filter(note=>note.subject===topic.name).length;return <Link key={topic.id} to={topic.path} className="group/topic flex items-center gap-3 rounded-xl border border-[#f0f1ed] bg-[#fcfcfa] p-3.5 transition hover:border-[#dce3d7] hover:bg-[#f8faf6]"><span className={`grid size-9 shrink-0 place-items-center rounded-[10px] ${topic.color==='sage'?'bg-[#edf2e9] text-[#74876d]':topic.color==='blue'?'bg-[#eef2f4] text-[#718e9d]':'bg-[#f7eee8] text-[#b38160]'}`}><TopicIcon size={17}/></span><span className="min-w-0 flex-1"><b className="block text-[12px] font-semibold text-[#4b5148]">{topic.name}</b><small className="mt-1 block text-[9px] text-[#a0a398]">{topic.description}</small></span><span className="hidden text-[9px] text-[#a0a398] sm:block">{topicNotes} notes</span><ArrowUpRight size={15} className="text-[#9ba692] transition group-hover/topic:translate-x-0.5 group-hover/topic:-translate-y-0.5"/></Link>})}</div></section>})}</div>
  </div>;
}
